
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Oct 27 16:24:52 CST 2013
//----------------------------------------------------

package translator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDE = 18;
  public static final int LT = 8;
  public static final int ELSE = 3;
  public static final int ENDIF = 4;
  public static final int EQUAL = 10;
  public static final int MULTI = 14;
  public static final int INTCONST = 16;
  public static final int IF = 2;
  public static final int GT = 7;
  public static final int LE = 6;
  public static final int EOF = 0;
  public static final int UNEQ = 9;
  public static final int DIV = 15;
  public static final int ADD = 12;
  public static final int GE = 5;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int RATIONAL = 17;
}

